# Generated by Django 4.2.7 on 2024-02-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taskTitle', models.CharField(max_length=50)),
                ('taskDescription', models.CharField(max_length=250)),
                ('is_completed', models.BooleanField()),
            ],
        ),
    ]
